# Generated by Django 2.1.7 on 2020-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190326_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='recruiter',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
