# Generated by Django 2.1.7 on 2020-02-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200204_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
