# Generated by Django 2.1.7 on 2020-02-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200208_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
