# Generated by Django 2.1.7 on 2020-02-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200208_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, default='images/member6.jpg', upload_to='images/'),
        ),
    ]
