# Generated by Django 2.1.7 on 2020-02-10 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200208_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
