# Generated by Django 2.1.7 on 2020-02-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upload',
        ),
    ]
