# Generated by Django 2.1.7 on 2020-02-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='user',
            name='hotel_Main_Img',
            field=models.FileField(default='o5.png', upload_to='images/'),
        ),
    ]
