# Generated by Django 2.1.7 on 2020-02-10 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200210_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
