# Generated by Django 2.1.7 on 2020-02-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200210_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
