# Generated by Django 2.1.7 on 2020-02-10 09:50

import accounts.managers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_hotel_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotel',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='recruiter',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
