# Generated by Django 2.1.7 on 2020-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200210_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='img/o5.png', upload_to='image/'),
        ),
    ]
