# Generated by Django 2.1.7 on 2020-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200210_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.FileField(upload_to=''),
        ),
    ]
