# Generated by Django 2.1.7 on 2020-02-13 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200213_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='recruiter',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('employer', 'Employer')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
