# Generated by Django 2.1.7 on 2020-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200213_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='user',
            name='recruiter',
            field=models.ManyToManyField(to='accounts.Choices'),
        ),
    ]
