# Generated by Django 2.1.7 on 2020-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200213_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='user',
            name='recruiter',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
