# Generated by Django 2.2 on 2020-02-16 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200216_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email1',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
