# Generated by Django 2.1.7 on 2020-02-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_job1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job1',
        ),
    ]
