# Generated by Django 2.2 on 2020-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_applicant1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant1',
            name='address',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='country',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='dob',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='dob_city',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='dob_country',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='dob_state',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='experience',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='job_title',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='location',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='mob',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='pin',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='state',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='tel',
            field=models.CharField(default='', max_length=90),
        ),
    ]
