# Generated by Django 2.2 on 2020-02-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0014_auto_20200221_0651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant1',
        ),
    ]
