# Generated by Django 2.2 on 2020-02-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20200216_1402'),
        ('jobsapp', '0015_delete_applicant1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
