# Generated by Django 2.2 on 2020-02-21 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0016_applicant1'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant1',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='company_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant1',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
