# Generated by Django 2.2 on 2020-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0017_auto_20200221_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='title',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='type',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applicant1',
            name='website',
        ),
        migrations.AddField(
            model_name='applicant1',
            name='address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='country',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='dob',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='dob_city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='dob_country',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='dob_state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='job_title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='mob',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='pin',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='applicant1',
            name='tel',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='experience',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='applicant1',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
    ]
