# Generated by Django 2.2 on 2020-02-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0018_auto_20200222_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant1',
            old_name='experience',
            new_name='experience1',
        ),
        migrations.RenameField(
            model_name='applicant1',
            old_name='location',
            new_name='location1',
        ),
    ]
