# Generated by Django 2.2 on 2020-02-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0021_auto_20200223_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant1',
        ),
    ]
