# Generated by Django 2.2 on 2020-02-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20200223_0710'),
        ('jobsapp', '0022_delete_applicant1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=12)),
                ('last_name1', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
