# Generated by Django 2.2 on 2020-02-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0023_applicant1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant1',
        ),
    ]
